# RealisticPlantGrowth configuration file
#
# Visit RealisticPlantGrowth's page on http://dev.bukkit.org for more config details.
#
# Full biome list available at https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/Biome.html
#
# Plants / Crops are available in the "Material" list.
# Full material list available at https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
#
# If you like this Plugin please consider leaving a donation <3
# ----------------------->  Donation LINK   <---------------------------------------------------


########################################################################################################################
#|                                                                                                                    |#
#| General Settings                                                                                                   |#
#|                                                                                                                    |#
########################################################################################################################
# Supported language codes under: /RealisticPlantGrowth/local
language_code: de-DE

# Plugin prefix shown in Console logs. Does not affect chat massages.
# Supports color miniMessage Format and Legacy &-ColorCodes (https://docs.advntr.dev/minimessage/format.html)
plugin_prefix: "&7[&2RealisticPlantGrowth&7] "

# Which worlds should this plugin be enabled in? Worlds not in this list will have default growth behavior.
enabled_worlds:
  - example_world
  - example_world_nether
  - example_world_end

# Limits the use of bonemeal on a single plant to the set amount.
# Use 'bonemeal_limit: 0' to completly forbid the use of bonemeal on plants
# Use negative numbers to disable this feature (e.g. bonemeal_limit: -1)
bonemeal_limit: 3

# Natural sky light level required for plants to grow.
# sky light level: 0: allows plants to growth underground. (light sources are still required.)
# sky light level 10: corresponds to sunlight through glass/tree leaves.
# sky light level 15: plants grow only in direct sunlight.
min_natural_light: 10

# Show players possible growth rates for an item they are holding in hand when left-clicking on the ground.
# Only growth rates for the biome, the player is standig in, are displayed.
report_growth: false

########################################################################################################################
#|                                                                                                                    |#
#| Fertilizer                                                                                                         |#
#|                                                                                                                    |#
#| Composters fertilizing corps in the surrounding area. This allows plant growth in normally inhabitable areas.      |#
#|                                                                                                                    |#
########################################################################################################################
# Enable use of composter fertilizer.
fertilizer_enabled: false

# Plants within this distance of Blocks will grow at fertilizer_growth_rate. (see below)
# Higher values require more server resources and may causing server lag. (max. 15 Blocks)
fertilizer_radius: 5

# true: fertilizer effects don't drain composters in order to fertilize the surroundings.
# false: requires the player to actively fill the composter to get the fertilizer effects.
fertilizer_passiv: true

# The fertilizer_boost_growth_rate represents a percentage value which is added on top of biome-specific growth rates,
# if a composter is within configured fertilizer_radius.
# For example: biome specific growth rate of wheat in a dessert is 20% so a fertilizer_boost_growth_rate of 25.0% leads
# to a growth value of 45.0% of wheat plants.
# Note that specific plant/biome dark and death rates take effect regardless of fertilizer.
fertilizer_boost_growth_rate: 20.0

# Should a growth_rate above 100.0% be allowed?
# If a plant has a biome specific growth rate of 100.0% and fertilizer_allow_growth_rate_above_100 is set to true,
# then the resulting growth rate is above 100.0% (e.g. 125.0%)
# Otherwise the growth_rate is capped at 100.0%
fertilizer_allow_growth_rate_above_100: true;

########################################################################################################################
#|                                                                                                                    |#
#| UV-Light                                                                                                           |#
#|                                                                                                                    |#
#| UV-Light is an artificial light source, that allows plants in radius to grow where the sky light value is lower    |#
#| than the min_natural_light value.                                                                                  |#
#| This allows the cultivation of plants underground or in buildings with no direkt sky light access.                 |#
#| Note: Plants still require a certain light level in order to grow.                                                 |#
#|                                                                                                                    |#
########################################################################################################################
# Enable use of UV Light Blocks
uv_enabled: false

# A List of Blocks that can act as UV Light (Doesn't need to be a light emitting block)
uv_blocks:
  - GLOWSTONE
  - CRYING_OBSIDIAN

# Radius around an UV-block that UV light affects.
# Higher values require more server resources and may causing server lag. (max. 15 Blocks)
uv_radius: 5

# List of items allowed to grow in artificial light (e.g. torches and lanterns (not the same as UV-Light))
# Use official MATERIAL_NAMES to add to this list (https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html)
grow_in_dark:
  - RED_MUSHROOM
  - BROWN_MUSHROOM
  - NETHER_WARTS
  - COCOA


########################################################################################################################
#|                                                                                                                    |#
#| Logging & Debugging                                                                                                |#
#|                                                                                                                    |#
#| Runs various debug logs to view additional plugin data for troubleshooting and configuration.                      |#
#|                                                                                                                    |#
########################################################################################################################
# Enables Debug-Mode. Can get spammy, use for only for debugging.
debug_log:    true

# Will additionally log Tree Growing Events in a separate log file.
tree_log:     false

# Will additionally log Plant Growing Events in a separate log file.
plant_log:    false

# Will additionally log Bonemeal Growing Events in a separate log file.
bonemeal_log: false

# Will additionally log the coordinates on the world of the event. (gets really spammy)
log_coords:   false


########################################################################################################################
#| Spooky internal settings.                                                                                          |#
#| Don't touch this pls =)                                                                                            |#
########################################################################################################################
config-version: 1
verbose: true