# Realistic Plant Growth Configuration File
#
# For additional configuration details and examples, visit the Realistic Plant Growth documentation at:
# https://realistic-plant-growth.nightevolution.de/
#
# A complete list of biomes can be found in the Spigot API documentation:
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/Biome.html
#
# Information on plants and crops can be referenced in the "Material" list at:
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
#
# If you appreciate this plugin, please consider showing your support with a donation.
# Your contributions help maintain and develop the plugin further. Thank you! ❤️
#
# Donation link: https://www.buymeacoffee.com/TheRealPredator
#
########################################################################################################################
#|                                                                                                                    |#
#| General Settings                                                                                                   |#
#|                                                                                                                    |#
########################################################################################################################

# Language setting for the plugin. Language files are located in /RealisticPlantGrowth/local
language_code: en-US

# List of worlds where this plugin is active. Worlds not listed here will use default growth behavior.
enabled_worlds:
  - your_world
  - your_world_nether
  - your_world_the_end

# When set to 'true', the world whitelist above will function as a world blacklist,
# enabling the plugin on all worlds except those listed.
use_enabled_worlds_as_world_blacklist: false

# Displays potential growth rates for an item in hand when a player left-clicks the ground.
# Only shows growth rates for the biome the player is currently in.
display_growth_rates: true

# Only active, if display_growth_rates is enabled.
# Time in seconds before the growth rates are shown to the player again.
# Prevents spam clicking and therefore heavy area scans.
display_cooldown: 5


########################################################################################################################
#|                                                                                                                    |#
#| Farmland Behavior                                                                                                  |#
#|                                                                                                                    |#
########################################################################################################################

# If enabled, farmland will be replaced with another block when a player harvests a plant growing on it.
# This feature forces players to re-till the soil before planting new crops.
farmland_settings:
  destroy_on_harvest: true # Enables farmland destruction upon harvest.

  # Define the blocks that can replace farmland when it is destroyed and their probabilities.
  # The format is: <BLOCK>: <PROBABILITY in %>
  replacement_blocks:
    DIRT: 75          # 75% chance for farmland to be replaced by dirt
    COARSE_DIRT: 25   # 25% chance for farmland to be replaced by coarse dirt


########################################################################################################################
#|                                                                                                                    |#
#| Composter Settings                                                                                                 |#
#|                                                                                                                    |#
#| Configuration options for customizing composter behavior and functionality in the game.                           |#
#|                                                                                                                    |#
########################################################################################################################

composter:
  # If enabled, composters will NOT produce bonemeal.
  # This also disables bonemeal farming via hopper-fed composters.
  disable_bonemeal_output: false

  # If enabled, allows players to rapidly fill composters by holding Shift and right-clicking
  # with compostable items. Speeds up manual composting.
  quick_fill_with_shift: false

  # If enabled, allows bonemeal to be added to composters by players or hoppers.
  # Each use of bonemeal increases the compost level by 1 (100% success rate).
  allow_bonemeal_as_input: false


########################################################################################################################
#|                                                                                                                    |#
#| Fertilizer                                                                                                         |#
#|                                                                                                                    |#
#| Enables Composters to fertilize crops in the surrounding area, allowing for growth in normally uninhabitable areas.|#
#|                                                                                                                    |#
########################################################################################################################

# Enables the use of composters to fertilize crops in the surrounding area.
fertilizer_enabled: false

# Plants within this block radius will grow at the 'fertilizer_growth_rate' (see below).
# Higher values may increase server resource consumption and cause lag (Maximum 15 blocks).
fertilizer_radius: 8

# true: Fertilizer effects do not deplete composters to fertilize the surroundings.
# false: Players must actively fill the composter to achieve fertilization effects.
fertilizer_passive: false

# Allows a growth rate above 100.0%.
# If a plant has a biome-specific growth rate of 100.0% and this is set to be true,
# the resulting growth rate can exceed 100.0% (e.g., 125.0%).
# Otherwise, the growth rate is capped at 100.0%.
fertilizer_allow_growth_rate_above_100: false

# If set to true, Fertilizer allows plants to thrive in 'invalid' biomes.
# If set to false, plant growth is limited to biomes explicitly listed in 'Biome' within GrowthModifiers.yml.
fertilizer_enables_growth_in_invalid_biomes: false

# Growth rate of plants in invalid biomes with fertilizer access.
# Only active if 'fertilizer_enables_growth_in_invalid_biomes' is set to 'true',
# and the plant is in an invalid biome.
fertilizer_invalid_biome_growth_rate: 20.0

# Probability of plant death in an invalid biome despite fertilizer supply.
# This rule is effective only when 'fertilizer_enables_growth_in_invalid_biomes'
# is set to 'true' and the plant is located in an inappropriate biome.
# If the Growth process of the plant consists of multiple growth stages, the death rate is internally
# adjusted by dividing it by the number of growth stages
fertilizer_invalid_biome_death_chance: 35.0


########################################################################################################################
#|                                                                                                                    |#
#| UV-Light                                                                                                           |#
#|                                                                                                                    |#
#| Artificial light source that allows plants within its radius to grow where the sky light level is lower            |#
#| than the 'min_natural_light' value. This allows the cultivation of plants underground or in buildings without      |#
#| direct sky light access.                                                                                           |#
#| Note: Plants still require a certain light level to grow.                                                          |#
#|                                                                                                                    |#
########################################################################################################################

# Enable use of UV-Light Blocks
uv_enabled: false

# Radius around a UV-Light block that affects growth.
# Higher values consume more server resources and may lead to server lag. (Maximum 15 blocks)
uv_radius: 5

# List of blocks that can function as UV-Light sources; they don't need to emit light.
uv_blocks:
  - OCHRE_FROGLIGHT
  - PEARLESCENT_FROGLIGHT
  - VERDANT_FROGLIGHT

# Determines whether a plant requires all UV-Light Blocks listed above to grow.
#   true: All blocks in 'uv_blocks' are necessary for plant growth.
#   false: Only one of the blocks listed in 'uv_blocks' is required for plant growth.
require_all_uv_blocks: true

# List of plants that grow without requiring natural sky light, allowing growth
# in artificial light sources like torches and lanterns (not the same as UV-Light).
# Use official MATERIAL_NAMES to add items to this list (https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html)
grow_in_dark:
  # Overworld plants
  - RED_MUSHROOM
  - BROWN_MUSHROOM
  - CAVE_VINES
  - GLOW_LICHEN
  # Ocean
  - KELP
  # End plants
  - CHORUS_FLOWER
  # Nether plants
  - WEEPING_VINES
  - TWISTING_VINES
  - NETHER_WART
  - WARPED_FUNGUS
  - CRIMSON_FUNGUS


########################################################################################################################
#|                                                                                                                    |#
#| Sounds & Effects                                                                                                   |#
#|                                                                                                                    |#
#| Configure played sounds or particle effects used by this plugin.                                                   |#
#|                                                                                                                    |#
#| Available sounds and effects:                                                                                      |#
#| Sound:            https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html                                   |#
#| Particle Effect:  https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Effect.html                                  |#
#|                                                                                                                    |#
########################################################################################################################

plant_death_sound_effect:
  # Enables the sound and particle effects for dying plants.
  enabled: true
  # The sound played when a plant dies. Choose from available sounds (link provided above).
  sound: BLOCK_CROP_BREAK
  # Adjust the volume (0.0 to 1.0).
  volume: 0.5
  # Adjust the pitch (0.5 to 2.0, 1.0 is normal pitch).
  pitch: 0.5
  # The particle effect played when a plant dies. Choose from available particle effects (link provided above).
  effect: SMOKE
  # Adjust effect data if applicable.
  data: 1

########################################################################################################################
#|                                                                                                                    |#
#| Logging & Debugging                                                                                                |#
#|                                                                                                                    |#
#| Enables various debug logs to provide additional plugin data for troubleshooting and configuration purposes.       |#
#| WARNING: Enable logging only for debugging purposes, as it can generate a large amount of data.                    |#
#|                                                                                                                    |#
########################################################################################################################

# Enable Debug Mode. This can generate a large amount of log data, so use it only for debugging purposes.
debug_log: false

# Enable logging of plant growing events in a separate log file.
plant_log: false

# Enable logging of tree growing events (e.g., sapling to tree, mushroom to huge mushroom) in a separate log file.
structure_log: false

# Enable logging of player interaction events in a separate log file.
player_log: false

# Enable logging of bonemeal usage events in a separate log file.
bonemeal_log: false


########################################################################################################################
#|                                                                                                                    |#
#| Plugin Management                                                                                                  |#
#|                                                                                                                    |#
#| Controls plugin update checks and anonymous metrics reporting.                                                     |#
#|                                                                                                                    |#
########################################################################################################################

# Update Checker
# Set 'enabled' to 'true' to allow the plugin to automatically check for updates.
# By default, the update check happens when the server starts.
#
# You can also set a custom interval for periodic update checks:
# - Use 'interval' (in hours) to specify how often to check for updates automatically.
# - Set 'interval' to -1 if you only want the update check to run once at startup.
#
# Setting 'enabled' to 'false' disables all automatic update checks.
update_check:
  enabled: true
  interval: 24

# bStats
# Please keep this enabled! It helps me understand what Minecraft versions and server setups are most common.
# No personal data is collected — just anonymous stats that help improve the plugin.
# bStats Link: https://bstats.org/plugin/bukkit/Realistic%20Plant%20Growth/20634
use_metrics: true


########################################################################################################################
#| Spooky internal settings.                                                                                          |#
#| Please do not modify. =)                                                                                           |#
########################################################################################################################
config-version: 8
verbose: false