package de.nightevolution.utils.enums;

public interface PlaceholderInterface {
    String PLANT_PLACEHOLDER = "{PLANT}";
    String GROWTH_RATE_PLACEHOLDER = "{GROWTH_RATE}";
    String DEATH_CHANCE_PLACEHOLDER = "{DEATH_CHANCE}";
    String BIOME_PLACEHOLDER = "{BIOME}";
    String IS_VALID_BIOME_PLACEHOLDER = "{IS_VALID_BIOME}";
    String FERTILIZER_USED_PLACEHOLDER = "{FERTILIZER_USED}";
    String UV_LIGHT_USED_PLACEHOLDER = "{UV_LIGHT_USED}";
    String CAN_GROW_IN_DARK_PLACEHOLDER = "{CAN_GROW_IN_DARK}";
    String IS_DARK_PLACEHOLDER = "{IS_DARK}";
    String BIOME_GROUP_LIST_PLACEHOLDER = "{BIOME_GROUP_LIST}";
    String BIOME_LIST_PLACEHOLDER = "{BIOME_LIST}";

}
